# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCasoautomatico1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_casoautomatico1(self):
    # Test name: Caso automatico 1
    # Step # | name | target | value
    # 1 | open | https://www.kayak.com/flights/SJO-ADZ/2022-07-14/2022-07-21?sort=bestflight_a | 
    self.driver.get("https://www.kayak.com/flights/SJO-ADZ/2022-07-14/2022-07-21?sort=bestflight_a")
    # 2 | setWindowSize | 1696x1026 | 
    self.driver.set_window_size(1696, 1026)
    # 3 | click | css=.yWJT-insideDrawer path | 
    self.driver.find_element(By.CSS_SELECTOR, ".yWJT-insideDrawer path").click()
    # 4 | click | linkText=Flights | 
    self.driver.find_element(By.LINK_TEXT, "Flights").click()
    # 5 | click | css=.c8LPF-icon | 
    self.driver.find_element(By.CSS_SELECTOR, ".c8LPF-icon").click()
  
