# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCasoautomatico4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_casoautomatico4(self):
    # Test name: Caso automatico 4
    # Step # | name | target | value
    # 1 | open | https://www.kayak.com/flights/SJO-ADZ/2022-07-14/2022-07-21?sort=bestflight_a | 
    self.driver.get("https://www.kayak.com/flights/SJO-ADZ/2022-07-14/2022-07-21?sort=bestflight_a")
    # 2 | setWindowSize | 1552x840 | 
    self.driver.set_window_size(1552, 840)
    # 3 | mouseOver | css=.yWJT-insideDrawer | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".yWJT-insideDrawer")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | mouseOut | css=.yWJT-insideDrawer | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 5 | click | css=.yWJT-insideDrawer .svg-image | 
    self.driver.find_element(By.CSS_SELECTOR, ".yWJT-insideDrawer .svg-image").click()
    # 6 | click | css=.hsCY:nth-child(4) > .hsCY-menu-item-title | 
    self.driver.find_element(By.CSS_SELECTOR, ".hsCY:nth-child(4) > .hsCY-menu-item-title").click()
    # 7 | click | linkText=See all | 
    self.driver.find_element(By.LINK_TEXT, "See all").click()
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
  
