# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCasoautomatico2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_casoautomatico2(self):
    # Test name: Caso automatico 2
    # Step # | name | target | value
    # 1 | open | https://www.kayak.com/flights/SJO-ADZ/2022-07-14/2022-07-21?sort=bestflight_a | 
    self.driver.get("https://www.kayak.com/flights/SJO-ADZ/2022-07-14/2022-07-21?sort=bestflight_a")
    # 2 | setWindowSize | 1552x840 | 
    self.driver.set_window_size(1552, 840)
    # 3 | click | css=.yWJT-insideDrawer .svg-image | 
    self.driver.find_element(By.CSS_SELECTOR, ".yWJT-insideDrawer .svg-image").click()
    # 4 | click | css=.UVLb:nth-child(2) > .hsCY:nth-child(3) > .hsCY-menu-item-title | 
    self.driver.find_element(By.CSS_SELECTOR, ".UVLb:nth-child(2) > .hsCY:nth-child(3) > .hsCY-menu-item-title").click()
    # 5 | click | css=.Gt8D-mod-padding-default:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".Gt8D-mod-padding-default:nth-child(1)").click()
    # 6 | click | css=.Gt8D:nth-child(1) .c3I-P-name | 
    self.driver.find_element(By.CSS_SELECTOR, ".Gt8D:nth-child(1) .c3I-P-name").click()
    # 7 | type | css=.k_my-mod-theme-default > .k_my-input | Costa
    self.driver.find_element(By.CSS_SELECTOR, ".k_my-mod-theme-default > .k_my-input").send_keys("Costa")
    # 8 | mouseUp | css=.c8XRu:nth-child(2) .c8XRu-covid-info-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".c8XRu:nth-child(2) .c8XRu-covid-info-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
