# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCasoautomatico3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_casoautomatico3(self):
    # Test name: Caso automatico 3
    # Step # | name | target | value
    # 1 | open | https://www.kayak.com/flights/SJO-ADZ/2022-07-14/2022-07-21?sort=bestflight_a | 
    self.driver.get("https://www.kayak.com/flights/SJO-ADZ/2022-07-14/2022-07-21?sort=bestflight_a")
    # 2 | setWindowSize | 1552x840 | 
    self.driver.set_window_size(1552, 840)
    # 3 | click | css=.yWJT-insideDrawer path | 
    self.driver.find_element(By.CSS_SELECTOR, ".yWJT-insideDrawer path").click()
    # 4 | click | css=.hsCY:nth-child(5) > .hsCY-menu-item-title | 
    self.driver.find_element(By.CSS_SELECTOR, ".hsCY:nth-child(5) > .hsCY-menu-item-title").click()
    # 5 | runScript | window.scrollTo(0,1870.4000244140625) | 
    self.driver.execute_script("window.scrollTo(0,1870.4000244140625)")
    # 6 | click | linkText=Las Vegas Vacations | 
    self.driver.find_element(By.LINK_TEXT, "Las Vegas Vacations").click()
    # 7 | click | css=#S-95-submit > .v-c-p | 
    self.driver.find_element(By.CSS_SELECTOR, "#S-95-submit > .v-c-p").click()
  
